### PR TITLE
Add docs for custom http header

### PR DESCRIPTION
**Pull request by take**
docs for commit 850c1c4f55ea02c56f8b7c1cd12e9431e9919ac6

### CODE REVIEW

**Comment by geemus** [comment]
Hmm. I would like to support it, but I'm not thrilled about the naming presently (and kind of forgot about that change). Could you describe how you are using it to provide some context? Thanks!

**Comment by take** [comment]
> but I'm not thrilled about the naming presently

yea me too :P 

I'm using a custom header for client authorization, the header's name is something like X-AppName-Api-Key.

how about ? `"http_header": { "X-App-Api-Key": "abcdef" }`

**Comment by geemus** [comment]
Yeah. I guess that seems like it might be kind of limiting. Also the `http` part seems redundant.

My gut feeling would be to just use a `headers` key and expect that the value was a schema. So the actual keys would be nested under a properties key and could have format info, description, etc. It also opens up the possibility of using `required` and similar things to specify which headers must be included.

What do you think?

**Comment by take** [comment]
@geemus 

I totally agree with you. Actually when I first tried to write the definitions for custom headers, I expected that kind of implementation.

But I guess those updates will break backward compatibility so I guess the steps will be

1. Add docs for the current implementation(this PR)
2. Update the implementation(like the design you posted above)
3. Update the docs

wdyt? :o

**Comment by geemus** [comment]
Sounds reasonable. Once we have made the changes I guess we can then just allow the old way to work, but maybe print a deprecation warning or something?

**Comment by geemus** [comment]
Would you be up for working on the updates?

**Comment by take** [comment]
> Once we have made the changes I guess we can then just allow the old way to work, but maybe print a deprecation warning or something?

Sounds nice :)

> Would you be up for working on the updates?

Yea sure! Think I'll be able to create the PR this weekend :)

**Comment by geemus** [comment]
Awesome, thanks for working through the ideas with me. I look forward to the PR and just let me know if you have further questions or concerns. Thanks!

**Comment by take** [comment]
np thank you too! :D

**Pull request merged**
