### PR TITLE
Handle primitive items in arrays

### PR DESCRIPTION
**Pull request by Igosuki**

### CODE REVIEW

**Comment by geemus** [comment]
I'm not sure I follow some of the reasons for the changes. Previously just leaned on command line conventions for this, ie things like `doc > schemata_slate.md.erb`. It seems that simpler style has advantages over adding that complexity internally, but I would like to understand better what you were working toward. Thanks!

**Comment by Igosuki** [comment]
Actually this is a missclick; we've added a ton of features to prmd over to our side and are ready to make a pull request.
This merge actually contains more features than advertised.

**Comment by Igosuki** [comment]
I'll close this and come back to you with properly rebased commits. Sorry about that

**Comment by geemus** [comment]
No worries. I suspected it might be something along those lines. Just let
me know if you have questions or anything I can help with. Thanks!

On Wed, Jun 24, 2015 at 4:54 PM, Guillaume Balaine <notifications@github.com

**Pull request closed without merging**
