### PR TITLE
Nested requred properties

### PR DESCRIPTION
**Pull request by ruprict**
Here's an attempt to solve [this issue](https://github.com/interagent/prmd/issues/177).  I added specs for various scenarios and used my fork to generate our docs. 

I made some assumptions that may not be kosher, such as requiring a parent attribute requires all the nested attributes. 

Regardless, this should get the dialogue going. :smile:

### CODE REVIEW

**Comment by ruprict** [comment]
*taps mic* Is this thing on? :wink:

**Comment by mathroc** [comment]
:+1:

**Comment by geemus** [comment]
Sorry for the delay, I was on vacation (and subsequently struggling to play catch up).

**Comment by geemus** [comment]
Overall looking good, but could you maybe take out the whitespace changes in lib/prmd/templates/schemata/helper.erb? It would make the spacing inconsistent (and makes the patch noisier/harder to see what is actually changing). I think beyond that I'll probably need to test a little, but then we should be able to bring this in. Thanks!

**Comment by ruprict** [comment]
Hey @geemus, no worries on the delay, I get it. :)  I put that helper file back where I found it, so should be good to go now.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
