### PR TITLE
Add better error checking

### PR DESCRIPTION
**Pull request by RX14**
I am on `jruby-1.7.16-d19` with prmd `0.6.2` at `d2897` and my rake tasks fail to run:
```
$ rake schema --trace
** Invoke schema (first_time)
** Invoke schema:combine (first_time)
** Execute schema:combine
rake aborted!
TypeError: can't convert nil into Hash
org/jruby/RubyHash.java:1737:in `merge!'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/bundler/gems/prmd-d28977070dcb/lib/prmd/core/combiner.rb:61:in `combine'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/bundler/gems/prmd-d28977070dcb/lib/prmd/commands/combine.rb:84:in `combine'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/bundler/gems/prmd-d28977070dcb/lib/prmd/commands/combine.rb:98:in `combine'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/bundler/gems/prmd-d28977070dcb/lib/prmd/rake_tasks/combine.rb:40:in `define'
org/jruby/RubyProc.java:271:in `call'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/task.rb:240:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
/home/rx14/.rvm/rubies/jruby-1.7.16-d19/lib/ruby/2.0/monitor.rb:211:in `mon_synchronize'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/task.rb:201:in `invoke_prerequisites'
org/jruby/RubyArray.java:1613:in `each'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/task.rb:178:in `invoke_with_call_chain'
/home/rx14/.rvm/rubies/jruby-1.7.16-d19/lib/ruby/2.0/monitor.rb:211:in `mon_synchronize'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/application.rb:106:in `top_level'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/application.rb:78:in `run'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/gems/rake-10.3.2/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/bin/rake:1:in `(root)'
org/jruby/RubyKernel.java:1101:in `eval'
/home/rx14/.rvm/gems/jruby-1.7.16-d19@satapi/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => schema => schema:combine
```

Rakefile:
```ruby
require "prmd/rake_tasks/combine"
require "prmd/rake_tasks/verify"
require "prmd/rake_tasks/doc"

repo_root = File.absolute_path("#{__dir__}/../../")

namespace :schema do
    Prmd::RakeTasks::Combine.new do |t|
        t.options[:meta] = "#{repo_root}/docs/schema/meta.json"
        t.paths << "#{repo_root}/docs/schema/schemata"
        t.output_file = "#{repo_root}/docs/schema/api.json"
    end

    Prmd::RakeTasks::Verify.new do |t|
        t.files << "#{repo_root}/docs/schema/api.json"
    end

    Prmd::RakeTasks::Doc.new do |t|
        t.files = { "#{repo_root}/docs/schema/api.json" => "#{repo_root}/docs/schema/api.md" }
    end
end

task schema: ["schema:combine", "schema:verify", "schema:doc"]
```

I am quite tired right now from troubleshooting right now so I must go to bed. I will provide more details if required in the morning.

### CODE REVIEW

**Comment by geemus** [comment]
Looks like this has drifted a bit. Should we try to fix it back up or maybe drop it and try again? Thanks!

**Comment by RX14** [comment]
I don't currently have time to fix up this pull-request, but attempts to add better error checking would be nice.

**Comment by geemus** [comment]
No problem, thanks for the update.

**Comment by geemus** [comment]
Also, if you haven't tried newer versions, I think they also improve the error handling (though through a different approach). So that might help you.

**Comment by geemus** [comment]
Closing this for now, but feel free to reopen when you get a chance (and I'll try to help get some other improved error checking in also). Thanks!

**Pull request closed without merging**
