### PR TITLE
Don't ignore array properties [Close #242]

### LINKED ISSUE #242: Don't ignore array type properties when generating markdown file
This might be related to #239 .

this is a part of my schema:

```json
                ]
              },
              "price_list": {
                "example": [
                  10000,
                  15000,
                  17000
                ],
                "items": {
                  "example": 10000,
                  "type": [
                    "integer"
                  ]
                }
              },
              "address_zip": {
                "type": [
```

And this is generated `.md` file:

```markdown
#### Required Parameters

| Name | Type | Description | Example |
| ------- | ------- | ------- | ------- |
| **ota_name** | *string* |  | `"xxx"` |
| **hotel_name** | *string* |  | `"xxx"` |
| **address_prefecture** | *string* |  | `"Tokyo"` |
| **address_city** | *string* |  | `"Minato"` |
```

the `price_list` property doesn't appear in the `.md` file because `array` property is ignored.

so I fixed this bug and will open a PR soon.

### PR DESCRIPTION
**Pull request by mmyoji**
> #242 

* Reflect array type properties to markdown file.

### CODE REVIEW

**Comment by geemus** [comment]
Could you share a sample schema that demonstrates this fix? I just wanted to run through it to make sure I understood and could see the effect. Thanks!

**Comment by mmyoji** [comment]
Thanks for your quick reply :smile: 

here are the samples:


#### schema.json

```json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema",
  "type": [
    "object"
  ],
  "definitions": {
    "listing": {
      "links": [
        {
          "description": "Create listing",
          "href": "/v1/listings",
          "method": "post",
          "rel": "create",
          "schema": {
            "properties": {
              "hotel_name": {
                "example": "jalan",
                "type": [
                  "string"
                ]
              },
              "price_list": {
                "example": [
                  10000,
                  15000,
                  17000
                ],
                "items": {
                  "type": [
                    "integer"
                  ]
                },
                "type": [
                  "array"
                ]
              },
              "address_zip": {
                "type": [
                  "string"
                ]
              },
              "address_prefecture": {
                "example": "Tokyo",
                "type": [
                  "string"
                ]
              },
              "address_city": {
                "example": "Minato",
                "type": [
                  "string"
                ]
              }
            },
            "required": [
              "hotel_name",
              "price_list",
              "address_prefecture",
              "address_city"
            ]
          },
          "title": "Create listing"
        }
      ],
      "properties": {
        "id": {
          "description": "ID",
          "example": 1,
          "type": [
            "integer"
          ]
        },
        "hotel_name": {
          "description": "Hotel name",
          "example": "Tokyu IN",
          "type": [
            "string"
          ]
        },
        "price_list": {
          "description": "a list of prices",
          "example": [
            1000,
            2000,
            3000
          ],
          "items": {
            "type": [
              "integer"
            ]
          },
          "type": [
            "array"
          ]
        },
        "min_price": {
          "description": "minimum price",
          "example": 1000,
          "type": [
            "integer"
          ]
        },
        "max_price": {
          "description": "max price",
          "example": 3000,
          "type": [
            "integer"
          ]
        },
        "address_zip": {
          "description": "zip code",
          "example": "1060032",
          "type": [
            "string"
          ]
        },
        "address_prefecture": {
          "description": "prefecture name",
          "example": "Tokyo",
          "type": [
            "string"
          ]
        },
        "address_city": {
          "description": "city name",
          "example": "Minato",
          "type": [
            "string"
          ]
        }
      },
      "required": [
        "id",
        "hotel_name",
        "price_list",
        "min_price",
        "max_price",
        "address_zip",
        "address_prefecture",
        "address_city"
      ],
      "title": "listing resource"
    }
  },
  "properties": {
    "listing": {
      "$ref": "#/definitions/listing"
    }
  },
  "description": "Sample api",
  "id": "sample_api",
  "links": [
    {
      "href": "http://api.sample.com",
      "rel": "self"
    }
  ],
  "title": "Sample API"
}
```

#### schema.md

generated by `prmd doc schema.json > schema.md` command.

```markdown
## <a name="resource-listing"></a>listing resource



### Attributes

| Name | Type | Description | Example |
| ------- | ------- | ------- | ------- |
| **id** | *integer* | ID | `1` |
| **hotel_name** | *string* | Hotel name | `"Tokyu IN"` |
| **price_list** | *array* | a list of prices | `[1000,2000,3000]` |
| **min_price** | *integer* | minimum price | `1000` |
| **max_price** | *integer* | max price | `3000` |
| **address_zip** | *string* | zip code | `"1060032"` |
| **address_prefecture** | *string* | prefecture name | `"Tokyo"` |
| **address_city** | *string* | city name | `"Minato"` |

### listing resource Create listing

Create listing

```
post /v1/listings
```

#### Required Parameters

| Name | Type | Description | Example |
| ------- | ------- | ------- | ------- |
| **hotel_name** | *string* |  | `"jalan"` |
| **price_list** | *array* |  | `[10000,15000,17000]` |
| **address_prefecture** | *string* |  | `"Tokyo"` |
| **address_city** | *string* |  | `"Minato"` |


#### Optional Parameters

| Name | Type | Description | Example |
| ------- | ------- | ------- | ------- |
| **address_zip** | *string* |  | `"example"` |


#### Curl Example

```bash
$ curl -n -X post http://api.sample.com/v1/listings \
  -H "Content-Type: application/json" \
 \
  -d '{
  "hotel_name": "jalan",
  "price_list": [
    10000,
    15000,
    17000
  ],
  "address_zip": "example",
  "address_prefecture": "Tokyo",
  "address_city": "Minato"
}'
```


#### Response Example

```
HTTP/1.1 201 Created
```

```json
{
  "id": 1,
  "hotel_name": "Tokyu IN",
  "price_list": [
    1000,
    2000,
    3000
  ],
  "min_price": 1000,
  "max_price": 3000,
  "address_zip": "1060032",
  "address_prefecture": "Tokyo",
  "address_city": "Minato"
}
```

```

**Comment by geemus** [comment]
Ah, I think I understand better now, thanks!

**Comment by mmyoji** [comment]
@geemus thanks!

**Pull request merged**
